fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
      address: 'belhadj.rached@gmail.com' # for example your email
      sender_name: 'belhadj.rached@gmail.com' # for example your email